HomeDecoration/Controllers/InvoiceController.cs
using HomeDecoration.Models.Domain;
using HomeDecoration.Models.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HomeDecoration.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        private readonly DatabaseContext _context;

        public InvoiceController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Invoices

        public async Task<IActionResult> Index()
        {
            return _context.Invoices != null
                ? View(await _context.Invoices.ToListAsync())
                : Problem("Entity set 'DatabaseContext.invoices'  is null.");
        }

        // GET: invoice/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Invoices == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoices.FirstOrDefaultAsync(
                m => m.Id == id
            );
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // GET: invoice/Create

        //public IActionResult Create()
        //{
        //    var model = new Invoice();
        //    var order = _context.Orders.ToList();
        //    Console.WriteLine(order);

        //    Replace `_context.Order.ToList()` with your logic to retrieve the Order list

        //    var ordertList = order
        //        .Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a. })
        //        .ToList();
        //    ViewBag.Order = ordertList;

        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(
        //    [Bind("Id,OrderId,Total_Amount,Payment_Status")]
        //    Invoice invoice
        //)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        invoice.CreatedAt = DateTime.Now;
        //        _context.Add(invoice);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }

        //    return View(invoice);
        //}

        // GET: invoice/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Invoices == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoices.FindAsync(id);
            if (invoice == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments.FirstOrDefaultAsync(p => p.InvoiceId == id);
            invoice.Payment = payment;
            return View(invoice);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            int id,
            [Bind("Id,OrderId,Total_Amount,Payment_Status")]
            Invoice invoice
        )
        {
            if (id != invoice.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (invoice.Payment != null)
                    {
                        _context.Update(invoice.Payment);
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!invoiceExists(invoice.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(invoice);
        }

        // GET: invoice/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Invoices == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoices.FirstOrDefaultAsync(m => m.Id == id);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // POST: invoice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Invoices == null)
            {
                return Problem("Entity set 'DatabaseContext.Invoices'  is null.");
            }
            var invoice = await _context.Invoices.FindAsync(id);
            if (invoice != null)
            {
                _context.Invoices.Remove(invoice);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool invoiceExists(int id)
        {
            return (_context.Invoices?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public ActionResult InvoiceIndex()
        {
            var model = _context.Invoices.Include("Order").ToList();
            return View(model);
        }

        // GET: invoice/Print/5
        public IActionResult Print(int id)
        {
            var invoices = _context.Invoices.FirstOrDefault(m => m.Id == id);
            return PartialView("_Print", invoices);
        }
    }
}

HomeDecoration/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HomeDecoration.Models.DTO;
using HomeDecoration.Models.Domain;
using static NuGet.Packaging.PackagingConstants;

namespace HomeDecoration.Controllers;

[Authorize]
public class OrderController : Controller
{
    private readonly DatabaseContext _context;

    public OrderController(DatabaseContext context)
    {
        _context = context;
    }

    // GET: Orders

    public async Task<IActionResult> Index()
    {
        return _context.Orders != null
            ? View(await _context.Orders.ToListAsync())
            : Problem("Entity set 'DatabaseContext.Orders'  is null.");
    }

    // GET: Orders/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Orders == null)
        {
            return NotFound();
        }

        var order = await _context.Orders.FirstOrDefaultAsync(
            m => m.Id == id
        );
        if (order == null)
        {
            return NotFound();
        }

        return View(order);
    }

    // GET: Orders/Create

    public IActionResult Create()
    {
        var model = new Order();
        var product = _context.Products.ToList();
        var customer = _context.Customers.ToList();
        Console.WriteLine($"Product: {string.Join(", ", product)}\nCustomer: {string.Join(", ", customer)}");

        // Replace `_context.Orders.ToList()` with your logic to retrieve the Orders list

        var productList = product
           .Select (a => new SelectListItem { Value = a.Id.ToString(), Text = a.Name })
            .ToList();
        ViewBag.Products = productList;

        var customerList = customer
         .Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Name })
          .ToList();
        ViewBag.Customers = customerList;

        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,CustomerId,ProductId,Total_Amount,Quantity")] Order order)
    {
        if (ModelState.IsValid)
        {
            // Retrieve the selected product based on the provided ProductId
            var product = await _context.Products.FindAsync(order.ProductId);
            if (product == null)
            {
                return NotFound();
            }

            // Set the Total_Amount of the order to the price of the selected product
            order.Total_Amount = product.Price * order.Quantity;

            _context.Add(order);
            await _context.SaveChangesAsync();

            var invoice = new Invoice()
            {
                OrderId = order.Id,
                Total_Amount = order.Total_Amount,
                CreatedAt = DateTime.Now,
                Payment_Status = "Not Paid"
            };
            _context.Invoices.Add(invoice);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        PopulateDropDownLists(order.ProductId, order.CustomerId);
        return View(order);
    }

    private void PopulateDropDownLists(int? selectedProductId = null, int? selectedCustomerId = null)
    {
        var products = _context.Products.ToList();
        var customers = _context.Customers.ToList();

        ViewBag.Products = new SelectList(products, "Id", "Name", selectedProductId);
        ViewBag.Customers = new SelectList(customers, "Id", "Name", selectedCustomerId);
    }



    // GET: Orders/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.Orders == null)
        {
            return NotFound();
        }

        var order = await _context.Orders.FindAsync(id);
        if (order == null)
        {
            return NotFound();
        }
        return View(order);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit( int id,[Bind("Id,CustomerId,ProductId,Total_Amount,Quantity")] Order order)
    {
        if (id != order.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(order);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrdersExists(order.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(order);
    }

    // GET: Orders/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Orders == null)
        {
            return NotFound();
        }

        var order = await _context.Orders.FirstOrDefaultAsync(m => m.Id == id);
        if (order == null)
        {
            return NotFound();
        }

        return View(order);
    }

    // POST: Orders/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_context.Orders == null)
        {
            return Problem("Entity set 'DatabaseContext.Orders'  is null.");
        }
        var order = await _context.Orders.FindAsync(id);
        if (order != null)
        {
            _context.Orders.Remove(order);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool OrdersExists(int id)
    {
        return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
    }

    public ActionResult OrderIndex()
    {
        var model = _context.Orders.Include(o => o.Product).Include(o => o.Customer).ToList();
        return View(model);
    }

    // GET: Orders/Print/5
    public IActionResult Print(int id)
    {
        var order = _context.Orders.FirstOrDefault(m => m.Id == id);
        return PartialView("_Print", order);
    }
}

HomeDecoration/Controllers/ProductController.cs
using HomeDecoration.Models.Domain;
using HomeDecoration.Models.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HomeDecoration.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly DatabaseContext _context;

        public ProductController(DatabaseContext context)
        {
            _context = context;
        }

        // GET:Products

        public async Task<IActionResult> Index()
        {
            return _context.Products != null ?
                         View(await _context.Products.ToListAsync()) :
                         Problem("Entity set 'DatabaseContext.Products'  is null.");
        }

        // GET:Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create

        [HttpGet]
        public IActionResult GetProductPrice(int id)
        {
            var product = _context.Products.FirstOrDefault(p => p.Id == id);
            if (product != null)
            {
                return Json(new { success = true, price = product.Price });
            }

            return Json(new { success = false });
        }
        public IActionResult Create()
        {
            return View();
        }

        //```csharp

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,Stock,Status")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.CreatedAt = DateTime.Now;
                product.Status = "Available";
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5    
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,Stock,Status")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'DatabaseContext.Products'  is null.");
            }
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsExists(int id)
        {
            return (_context.Products?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        // GET: product/Print/5
        public IActionResult Print(int id)
        {
            var product = _context.Products.FirstOrDefault(m => m.Id == id);
            return PartialView("_Print", product);
        }

    }
}

HomeDecoration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeDecoration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Maria_Home_Decor.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="style.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
            integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
            crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
            integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
            crossorigin="anonymous"></script>

</head>

<body>
    <div class="d-flex bg-white" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 info-text fs-4 fw-bold text-uppercase border-bottom">
                Dashboard
            </div>
            <div class="list-group list-group-flush my-3">
                <a class="list-group-item list-group-item-action bg-info shadow text-white rounded-2 m-2 second-text fw-bold" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-home me-2"></i>Home
                </a>
                <a class="list-group-item list-group-item-action bg-info shadow text-white rounded-2 m-2 second-text fw-bold"
                   asp-controller="Customer" asp-action="Index">
                    <i class="fas fa-user me-2"></i>Customer
                </a>
                <a class="list-group-item list-group-item-action bg-info shadow text-white rounded-2 m-2 second-text fw-bold"
                   asp-controller="Order" asp-action="Index">
                    <i class="fas fa-user me-2"></i>Order
                </a>
                <a class="list-group-item list-group-item-action bg-info shadow text-white rounded-2 m-2 second-text fw-bold" asp-controller="Product" asp-action="Index">
                    <i class="fas fa-box me-2"></i>Product
                </a>
                <a class="list-group-item list-group-item-action bg-info shadow text-white rounded-2 m-2 second-text fw-bold" asp-controller="Invoice" asp-action="Index">
                    <i class="fas fa-file-invoice-dollar me-2"></i>Invoices
                </a>
                @if (User.IsInRole("Admin"))
                {
                    <a class="list-group-item list-group-item-action bg-info shadow text-white rounded-2 m-2 second-text fw-bold"
                       asp-controller="Order" asp-action="Index">
                        <i class="fas fa-tachometer-alt me-2"></i>Order
                    </a>
                    <a class="list-group-item list-group-item-action bg-info shadow text-white rounded-2 m-2 second-text fw-bold"
                       asp-controller="Product" asp-action="Index">
                        <i class="fas fa-tachometer-alt me-2"></i>Product
                    </a>
                    <a class="list-group-item list-group-item-action bg-info shadow text-white rounded-2 m-2 second-text fw-bold"
                       asp-controller="Invoices" asp-action="Index">
                        <i class="fas fa-tachometer-alt me-2"></i>Invoices
                    </a>
                    <a class="list-group-item list-group-item-action bg-info shadow text-white rounded-2 m-2 second-text fw-bold"
                       asp-controller="User" asp-action="Index">
                        <i class="fas fa-tachometer-alt me-2"></i>Users
                    </a>
                }
            </div>
            <div class="list-group list-group-flush my-3">
                <a href="@Url.Action("Logout","UserAuthen")" class="list-group-item list-group-item-action bg-danger shadow text-white rounded-2 m-2 second-text fw-bold">
                    <i class="fas fa-power-off me-2"></i>Logout
                </a>
            </div>
        </div>
        <!-- Page Content -->
        <div id="page-content-wrapper" class="bg-white w-100">
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-4 px-4">
                <div class="d-flex align-items-center">
                    <img src="~/MariaHome.PNG" width="200" height="100" />
                    @* <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i> *@
                    <h2 class="fs-4 text-uppercase font-weight-bold m-0 text-info mx-2">
                        Dashboard Of Maria_Home_Decor Management System
                    </h2>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle text-capitalize second-text fw-bold"
                               id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-user me-2"></i>@User.Identity.Name
                            </a>
                        </li>
                        <ul class="navbar-nav mr-auto">
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" href="/Report/Index">Generate Report</a>
                                </li>
                            }
                        </ul>
                    </ul>
                </div>
            </nav>

            <div class="container-fluid px-4 bg-white">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - sample - <a asp-area="" asp-controller="Home" asp-action="privacy">privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>